# fly.toml app configuration file generated for fsopen-notes-abdi on 2023-06-23T18:49:21+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fsopen-notes-abdi"
primary_region = "syd"

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
