# fly.toml app configuration file generated for little-fire-9122 on 2023-05-28T16:22:46+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "little-fire-9122"
primary_region = "syd"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
